### PR TITLE
Firebase db mock

### PR DESCRIPTION
**Pull request by ayman-mezghani**

### CODE REVIEW

**Comment by ayman-mezghani** [comment]
@samuelchassot 

Hi Samuel, I hope you're fine.

Can you take a look at the way I implemented the mock for the database ?

I created an interface, then a MockDatabase in the Test folder that has a constructor that takes expected values and test whether the methods were called with the expected values. Then the DbAdapterTest just instantiates the Mock and injects it into a DbAdapter then performs the calls.

From now on, I think that we can just inject the mock in the tests. The expected values can help controlling the behavior depending on the values returned from the read method (since it just returns the expected value set in the constructor).

Let me know what you think.

Ayman

**Comment by samuelchassot** [comment]
> @samuelchassot
> 
> Hi Samuel, I hope you're fine.
> 
> Can you take a look at the way I implemented the mock for the database ?
> 
> I created an interface, then a MockDatabase in the Test folder that has a constructor that takes expected values and test whether the methods were called with the expected values. Then the DbAdapterTest just instantiates the Mock and injects it into a DbAdapter then performs the calls.
> 
> From now on, I think that we can just inject the mock in the tests. The expected values can help controlling the behavior depending on the values returned from the read method (since it just returns the expected value set in the constructor).
> 
> Let me know what you think.
> 
> Ayman

Hi Ayman,

I am fine, thanks :) hope you're are okay too!

I checked your code and the way you implemented the Database with the interface and the wrapper is great!

How you call the DB in the activities will bring you problems though, specially when testing. But don't panic, you're almost there, the changes required are small ;)

The whole idea of mocking the DB as you did is to be able to test the app just as a DB were connected. You will be able to test all activities just as normal except that the data will come from the mock and not from Firebase. So you'll be able to test everything as you would if you would rely on Firebase (hope this is clear enough, don't hesitate to ask if it's not).

But to achieve this, you need a way to inject the mock DB instead of the real Firebase one "without the activities even being able to notice it". Now, as you create the FirebaseDatabase instance and pass it to DatabaseWrapper in the Activities code, you won't be able to replace it by the mocked one. So you need something to provide a Database wrapper to activities that need one, so that you would inject there the mock in the tests.

The way I would do it is the following:
- Create a new class that will provide a DatabaseWrapper. This class will be a sort of singleton. When a get method is called, it will either provide the instance it contains or initialize it with a fresh one if the field is uninitialized. 
- Then add a way to force the initialization to a given DatabaseWrapper instance.

Then in every activity where you need a DB access, you get you DatabaseWrapper by asking this "provider".
Now in the tests you just call the "initialize" method first with a DatabaseWrapper that contains an instance of the mockDatabase and so every activity will get a DatabaseWrapper that contains a mockDB.

Hope this is clear, let me know if it is not.

Best,

Samuel

**Comment by ayman-mezghani** [comment]
> > @samuelchassot
> > Hi Samuel, I hope you're fine.
> > Can you take a look at the way I implemented the mock for the database ?
> > I created an interface, then a MockDatabase in the Test folder that has a constructor that takes expected values and test whether the methods were called with the expected values. Then the DbAdapterTest just instantiates the Mock and injects it into a DbAdapter then performs the calls.
> > From now on, I think that we can just inject the mock in the tests. The expected values can help controlling the behavior depending on the values returned from the read method (since it just returns the expected value set in the constructor).
> > Let me know what you think.
> > Ayman
> 
> Hi Ayman,
> 
> I am fine, thanks :) hope you're are okay too!
> 
> I checked your code and the way you implemented the Database with the interface and the wrapper is great!
> 
> How you call the DB in the activities will bring you problems though, specially when testing. But don't panic, you're almost there, the changes required are small ;)
> 
> The whole idea of mocking the DB as you did is to be able to test the app just as a DB were connected. You will be able to test all activities just as normal except that the data will come from the mock and not from Firebase. So you'll be able to test everything as you would if you would rely on Firebase (hope this is clear enough, don't hesitate to ask if it's not).
> 
> But to achieve this, you need a way to inject the mock DB instead of the real Firebase one "without the activities even being able to notice it". Now, as you create the FirebaseDatabase instance and pass it to DatabaseWrapper in the Activities code, you won't be able to replace it by the mocked one. So you need something to provide a Database wrapper to activities that need one, so that you would inject there the mock in the tests.
> 
> The way I would do it is the following:
> 
>     * Create a new class that will provide a DatabaseWrapper. This class will be a sort of singleton. When a get method is called, it will either provide the instance it contains or initialize it with a fresh one if the field is uninitialized.
> 
>     * Then add a way to force the initialization to a given DatabaseWrapper instance.
> 
> 
> Then in every activity where you need a DB access, you get you DatabaseWrapper by asking this "provider".
> Now in the tests you just call the "initialize" method first with a DatabaseWrapper that contains an instance of the mockDatabase and so every activity will get a DatabaseWrapper that contains a mockDB.
> 
> Hope this is clear, let me know if it is not.
> 
> Best,
> 
> Samuel

Hello, I'm good thank you !

I thought about forcing the Database instance to be a mock instance in the tests by accessing the variable (but in that case we'll have to set the variable to protected instead of private)

Otherwise, I found a way that checks whether the code is being executed from an espresso package or not, in other words it checks whether the app is being tested or used normally. Maybe we can use that to determine which Database type to pass.

Ayman

**Comment by samuelchassot** [comment]
> > > @samuelchassot
> > > Hi Samuel, I hope you're fine.
> > > Can you take a look at the way I implemented the mock for the database ?
> > > I created an interface, then a MockDatabase in the Test folder that has a constructor that takes expected values and test whether the methods were called with the expected values. Then the DbAdapterTest just instantiates the Mock and injects it into a DbAdapter then performs the calls.
> > > From now on, I think that we can just inject the mock in the tests. The expected values can help controlling the behavior depending on the values returned from the read method (since it just returns the expected value set in the constructor).
> > > Let me know what you think.
> > > Ayman
> > 
> > 
> > Hi Ayman,
> > I am fine, thanks :) hope you're are okay too!
> > I checked your code and the way you implemented the Database with the interface and the wrapper is great!
> > How you call the DB in the activities will bring you problems though, specially when testing. But don't panic, you're almost there, the changes required are small ;)
> > The whole idea of mocking the DB as you did is to be able to test the app just as a DB were connected. You will be able to test all activities just as normal except that the data will come from the mock and not from Firebase. So you'll be able to test everything as you would if you would rely on Firebase (hope this is clear enough, don't hesitate to ask if it's not).
> > But to achieve this, you need a way to inject the mock DB instead of the real Firebase one "without the activities even being able to notice it". Now, as you create the FirebaseDatabase instance and pass it to DatabaseWrapper in the Activities code, you won't be able to replace it by the mocked one. So you need something to provide a Database wrapper to activities that need one, so that you would inject there the mock in the tests.
> > The way I would do it is the following:
> > ```
> > * Create a new class that will provide a DatabaseWrapper. This class will be a sort of singleton. When a get method is called, it will either provide the instance it contains or initialize it with a fresh one if the field is uninitialized.
> > 
> > * Then add a way to force the initialization to a given DatabaseWrapper instance.
> > ```
> > 
> > 
> > Then in every activity where you need a DB access, you get you DatabaseWrapper by asking this "provider".
> > Now in the tests you just call the "initialize" method first with a DatabaseWrapper that contains an instance of the mockDatabase and so every activity will get a DatabaseWrapper that contains a mockDB.
> > Hope this is clear, let me know if it is not.
> > Best,
> > Samuel
> 
> Hello, I'm good thank you !
> 
> I thought about forcing the Database instance to be a mock instance in the tests by accessing the variable (but in that case we'll have to set the variable to protected instead of private)
> 
> Otherwise, I found a way that checks whether the code is being executed from an espresso package or not, in other words it checks whether the app is being tested or used normally. Maybe we can use that to determine which Database type to pass.
> 
> Ayman

Hi,

glad to ear that you're ok :)

the idea of modifying de content of the field directly is feasible but you need to modify an access modifier (from private to protected) only for testing purpose. It means that the fact that you're writing tests influences how you design your software and that's bad. If a field is private in your design, it should not become protected ONLY for tests.
The idea I gave to you is better in this sense (and it is a bit more efficient as you don't create many instances of the DatabaseWrapper).

The second idea you mentioned could be okay only if the test is done in the test class and not in production code. In the latter, the problem is the same as for the first solution: you have some test code in the production codebase, which is really bad.

You should really consider doing what I suggested as it is a good pattern and makes your code more elegant and more maintainable (imagine you want to implement a second type of DB in addition to Firebase and let the user decide. With the provider that I proposed, it is straight forward to add it to your code (it is not only my idea by the way, it is the standard way of handling this kind of stuff, you can read about MVVM and the class Repository, it is very similar). It is useful for tests and mocking but not only ;)


@Gondolav FYI

**Comment by ayman-mezghani** [comment]
> 
> 
> > > > @samuelchassot
> > > > Hi Samuel, I hope you're fine.
> > > > Can you take a look at the way I implemented the mock for the database ?
> > > > I created an interface, then a MockDatabase in the Test folder that has a constructor that takes expected values and test whether the methods were called with the expected values. Then the DbAdapterTest just instantiates the Mock and injects it into a DbAdapter then performs the calls.
> > > > From now on, I think that we can just inject the mock in the tests. The expected values can help controlling the behavior depending on the values returned from the read method (since it just returns the expected value set in the constructor).
> > > > Let me know what you think.
> > > > Ayman
> > > 
> > > 
> > > Hi Ayman,
> > > I am fine, thanks :) hope you're are okay too!
> > > I checked your code and the way you implemented the Database with the interface and the wrapper is great!
> > > How you call the DB in the activities will bring you problems though, specially when testing. But don't panic, you're almost there, the changes required are small ;)
> > > The whole idea of mocking the DB as you did is to be able to test the app just as a DB were connected. You will be able to test all activities just as normal except that the data will come from the mock and not from Firebase. So you'll be able to test everything as you would if you would rely on Firebase (hope this is clear enough, don't hesitate to ask if it's not).
> > > But to achieve this, you need a way to inject the mock DB instead of the real Firebase one "without the activities even being able to notice it". Now, as you create the FirebaseDatabase instance and pass it to DatabaseWrapper in the Activities code, you won't be able to replace it by the mocked one. So you need something to provide a Database wrapper to activities that need one, so that you would inject there the mock in the tests.
> > > The way I would do it is the following:
> > > ```
> > > * Create a new class that will provide a DatabaseWrapper. This class will be a sort of singleton. When a get method is called, it will either provide the instance it contains or initialize it with a fresh one if the field is uninitialized.
> > > 
> > > * Then add a way to force the initialization to a given DatabaseWrapper instance.
> > > ```
> > > 
> > > 
> > > Then in every activity where you need a DB access, you get you DatabaseWrapper by asking this "provider".
> > > Now in the tests you just call the "initialize" method first with a DatabaseWrapper that contains an instance of the mockDatabase and so every activity will get a DatabaseWrapper that contains a mockDB.
> > > Hope this is clear, let me know if it is not.
> > > Best,
> > > Samuel
> > 
> > 
> > Hello, I'm good thank you !
> > I thought about forcing the Database instance to be a mock instance in the tests by accessing the variable (but in that case we'll have to set the variable to protected instead of private)
> > Otherwise, I found a way that checks whether the code is being executed from an espresso package or not, in other words it checks whether the app is being tested or used normally. Maybe we can use that to determine which Database type to pass.
> > Ayman
> 
> Hi,
> 
> glad to ear that you're ok :)
> 
> the idea of modifying de content of the field directly is feasible but you need to modify an access modifier (from private to protected) only for testing purpose. It means that the fact that you're writing tests influences how you design your software and that's bad. If a field is private in your design, it should not become protected ONLY for tests.
> The idea I gave to you is better in this sense (and it is a bit more efficient as you don't create many instances of the DatabaseWrapper).
> 
> The second idea you mentioned could be okay only if the test is done in the test class and not in production code. In the latter, the problem is the same as for the first solution: you have some test code in the production codebase, which is really bad.
> 
> You should really consider doing what I suggested as it is a good pattern and makes your code more elegant and more maintainable (imagine you want to implement a second type of DB in addition to Firebase and let the user decide. With the provider that I proposed, it is straight forward to add it to your code (it is not only my idea by the way, it is the standard way of handling this kind of stuff, you can read about MVVM and the class Repository, it is very similar). It is useful for tests and mocking but not only ;)
> 
> @Gondolav FYI

Hello,

One last question to make sure I understand well.

We'll have a generator/provider class that has a static variable set by default to "prod", and a method allowing us to set this variable to "test" that will trigger the generation of a mock instead of the Firebase instance, while having the mock class in the main package.
Or should we be passing the mock/prod db to the provider while keeping the mock in the test/AndroidTest package ? The latter may cause some accessibility issues as putting the mock in one package will make it inaccessible in the other therefore we won't be able to use it for unit testing and instrumented testing.

Thanks,

Ayman

**Comment by samuelchassot** [comment]
Hi,

Once again, you should not have anything related to testing in the production code. So the first option is not good.
The provider contains a field containing a DatabaseWrapper instance, initialized by default with a FirebaseDatabase instance when the get method is called the first time. The provider also provides a method set that let you pass a DatabaseWrapper instance to set manually the field, that will let you inject the mock.
The mock stays in AndroidTest, but if you mirrored the structure of packages as in the prod one, it will be recognized by other classes as if it was in the prod package.

Hope this is clearer now, don't hesitate to ask if it isn't.

Best,

Samuel

**Comment by ayman-mezghani** [comment]
> Hi,
> 
> Once again, you should not have anything related to testing in the production code. So the first option is not good.
> The provider contains a field containing a DatabaseWrapper instance, initialized by default with a FirebaseDatabase instance when the get method is called the first time. The provider also provides a method set that let you pass a DatabaseWrapper instance to set manually the field, that will let you inject the mock.
> The mock stays in AndroidTest, but if you mirrored the structure of packages as in the prod one, it will be recognized by other classes as if it was in the prod package.
> 
> Hope this is clearer now, don't hesitate to ask if it isn't.
> 
> Best,
> 
> Samuel

Hello,

Thank you for the help. I think it's all good now. :)

Ayman

**Pull request merged**
