### PR TITLE
Feature/database setup

### PR DESCRIPTION
**Pull request by ayman-mezghani**

### CODE REVIEW

**Comment by ayman-mezghani** [comment]
ignoring the google json file causes build to fail.

**Comment by ayman-mezghani** [comment]
@samuelchassot @Gondolav We need some help here.
I'm currently adding the firebase dependencies to the app. These dependencies need a file called google-services.json which contains some api-keys and I believe we shouldn't push this file to the public repo since it contains some sensitive information. But not pushing that file causes the app not to build on Travis since Travis doesn't have access to the file. Have you ever experienced such an issue? Do you have any ideas on how to solve this issue ?

**Comment by Gondolav** [comment]
> @samuelchassot @Gondolav We need some help here.
> I'm currently adding the firebase dependencies to the app. These dependencies need a file called google-services.json which contains some api-keys and I believe we shouldn't push this file to the public repo since it contains some sensitive information. But not pushing that file causes the app not to build on Travis since Travis doesn't have access to the file. Have you ever experienced such an issue? Do you have any ideas on how to solve this issue ?

I think you can push it as it doesn't contain sensitive information. However, if you want to hide it, maybe [this article]( https://proandroiddev.com/configure-firebase-project-for-continuous-integration-builds-833f08561a73) could help you.

**Comment by samuelchassot** [comment]
> @samuelchassot @Gondolav We need some help here.
> I'm currently adding the firebase dependencies to the app. These dependencies need a file called google-services.json which contains some api-keys and I believe we shouldn't push this file to the public repo since it contains some sensitive information. But not pushing that file causes the app not to build on Travis since Travis doesn't have access to the file. Have you ever experienced such an issue? Do you have any ideas on how to solve this issue ?

Hey, I personally would push it to the repo, won't be problematic. You will need to share the key with your friend in a config file of Android studio too.

**Comment by ayman-mezghani** [comment]
okay thanks for the tips :)

**Comment by ayman-mezghani** [comment]
Dependencies updated

**Comment by ayman-mezghani** [comment]
@seboll13 @JulienHu could you please review my pull request ? I'm planning on merging it Tuesday evening at the latest. Thanks

**Pull request merged**
